// AUTO-SEED of the e2e combination matrix registry — source of truth for coverage.
// Rich per-scenario detail (rationale/fixture/drive/assertions) lives in
// docs/superpowers/specs/2026-06-13-e2e-combination-matrix-design.md Appendix A, keyed by id.
// The check:matrix drift-guard asserts every entry has a `[<id>]` marker in each
// declared mode's test file(s). Do NOT hand-edit ids; add a row when a scenario is added.

export type Mode = "direct" | "workflow";
export type Legality = "valid" | "reject";
export type Coverage = "new" | "extends-existing" | "duplicate";

export interface Scenario {
  id: string;
  title: string;
  axes: string[];
  legality: Legality;
  modes: Mode[];
  risk: "high" | "med" | "low";
  coverage: Coverage;
  /** Phase that lands this scenario: 1 direct/reject, 2 wf single-token, 3 wf concurrency (@needs-task54). */
  phase: 1 | 2 | 3;
  /** Test file carrying the `[id]` marker per mode ('' = not applicable in that mode). */
  directFile: string;
  workflowFile: string;
}

export const SCENARIOS: Scenario[] = [
  { id: "C-AND-2BRANCH-01", title: "2-branch AND fork/join \u2014 forward completion + Workflow-mode liveness (L6.6 hang detector)", axes: ["Concurrency:fan-out", "Gateways:parallelGateway", "Activities:serviceTask", "Replay:multi-wait"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-3ASYM-01", title: "3-branch asymmetric AND \u2014 short branches park at join until the long branch drains (last-token-out)", axes: ["Concurrency:fan-out", "Concurrency:join-barrier", "Gateways:parallelGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/concurrency.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-VARMERGE-01", title: "Branch-local overlay isolation + merge-order conflict (later doc-order branch wins)", axes: ["Concurrency:overlay", "Concurrency:merge-order", "Gateways:parallelGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-NESTED-01", title: "Nested laminar AND-in-AND \u2014 inner join folds onto the enclosing branch token", axes: ["Concurrency:nesting", "Gateways:parallelGateway", "Replay:multi-wait"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-INTX-01", title: "AND fork/join wholly inside a transaction \u2014 forward commit, no failure", axes: ["Concurrency", "Activities:transaction", "Gateways:parallelGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-BTIMER-01", title: "Interrupting boundary timer fires ON a parallel-branch service task \u2014 sibling continues (timer WINS)", axes: ["Events:boundaryTimer", "Concurrency:fan-out", "Gateways:parallelGateway", "Replay:timer-self-heal"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/concurrency.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-AND-BTIMER-02", title: "Branch boundary timer LOSES \u2014 job completes first; the armed branch timer's later alarm is a no-op on the branch token, not root", axes: ["Events:boundaryTimer", "Concurrency:overlay", "Replay:timer-self-heal", "Replay:apply-from-D1"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/concurrency.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-OR-SUBSET-01", title: "Inclusive OR activation subsets (1-of-3, 2-of-3, all-3, default) \u2014 join over recorded subset", axes: ["Gateways:inclusiveGateway", "Concurrency:OR-subset", "Flows:conditional", "Flows:default"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/inclusive-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-OR-NOPATH-01", title: "OR split with zero activation and no default -> noPath terminal mid-concurrency", axes: ["Gateways:inclusiveGateway", "Error:noPath", "Flows:conditional"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/inclusive-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-OR-NESTAND-01", title: "OR-split branch containing a nested AND fork/join (mixed nesting)", axes: ["Gateways:inclusiveGateway", "Gateways:parallelGateway", "Concurrency:nesting"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/concurrency.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-ITIMER-01", title: "Intermediate catch timer (single ISO-8601 delay) inside a parallel branch", axes: ["Events:intermediateTimer", "Concurrency:fan-out"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/concurrency.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-MSG-01", title: "Distinct message intermediate catches per branch \u2014 apply-from-D1 routing to own overlay", axes: ["Events:messageCatch", "Idempotency:correlation", "Concurrency:overlay", "Replay:apply-from-D1"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-message.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-EBG-01", title: "eventBasedGateway inside a parallel branch \u2014 winner on branch overlay + loser (timer) settlement", axes: ["Gateways:eventBasedGateway", "Events:messageCatch", "Events:timer", "Concurrency:overlay"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/event-gateway.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-STRAGGLER-01", title: "Straggler completion after cancel begins \u2014 ledgered then compensated in lineage", axes: ["Compensation:straggler", "Concurrency", "Operator:cancel"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-QUIESCE-01", title: "Quiescence barrier \u2014 saga-failed settles only when ledger drained AND all cohort tokens terminal (steady-state, no crash)", axes: ["Compensation:quiescence", "Concurrency", "Replay:multi-wait"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-FAILED-01", title: "compensationFailed mid-reverse in one lineage -> compensationFailure incident, operator-resumable (both branches already terminal)", axes: ["Compensation:failure", "Error:compensationFailure", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-FAILED-INFLIGHT-01", title: "compensationFailed declared in one lineage while a SIBLING cohort token is still in-flight \u2014 no leak, barrier-aware", axes: ["Compensation:failure", "Compensation:quiescence", "Error:compensationFailure", "Concurrency:in-flight-token"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-LINEAGE-REVERSE-01", title: "Per-lineage reverse-order compensation over a MULTI-STEP branch (cross-branch order unconstrained)", axes: ["Compensation:per-lineage-reverse", "Concurrency:lineage-quiescence", "Gateways:parallelGateway", "Activities:transaction"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-NESTEDTX-BRANCH-01", title: "Transaction nested INSIDE one parallel branch \u2014 inner commit is committedLocal; outer cancel DOES re-compensate it (M5-L1 commit shield)", axes: ["Compensation:scope-nesting", "Compensation:commit-shield", "Activities:transaction", "Concurrency:fan-out", "Gateways:parallelGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/nested-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-COMP-LOOP-BRANCH-01", title: "Loop inside a parallel branch then cancel \u2014 per-occurrence reverse compensation within a NON-ROOT lineage (token_id set)", axes: ["Compensation:per-lineage-reverse", "Loops:occurrence", "Concurrency:lineage-quiescence", "Activities:transaction"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-IDEMP-COMP-DUP-01", title: "At-least-once on the COMPENSATION callback \u2014 duplicate comp-job complete / replayed wait-comp advances the reverse pass once", axes: ["Idempotency:dupCompensation", "Compensation", "Replay:apply-from-D1", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-ERR-BRANCH-COMP-01", title: "Branch business-error redirect inside a tx, then cancel \u2014 failed-then-routed step owes NO compensation; only the redirect-target ledgers", axes: ["Compensation", "Events:errorBoundary", "Error:routing", "Concurrency:fan-out"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-ERR-PRECEDENCE-01", title: "Error-boundary on a branch task \u2014 confinement + precedence ladder (exact @errorCode beats catch-all; non-matching -> catch-all; none -> Hazard), sibling continues to join", axes: ["Events:errorBoundary", "Error:routing", "Error:precedence", "Concurrency:fan-out"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/error-routing.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-ERR-HAZARD-01", title: "Uncaught error in one branch -> Hazard freezes instance (no wedge), sibling frozen, then /cancel reverse pass", axes: ["Error:Hazard", "Compensation", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-NOPATH-01", title: "XOR/OR split inside one AND branch dead-ends (noPath/conditionFailure) while sibling in flight", axes: ["Error:noPath", "Error:conditionFailure", "Concurrency", "Gateways:exclusiveGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/errors.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-CAP-TRIO-01", title: "Concurrency caps trio under load \u2014 concurrencyLimit, stepBudget, join-payload poison", axes: ["Concurrency:caps", "Error:concurrencyLimit", "Error:stepBudget", "Error:poison"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-caps.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-POISON-01", title: "Branch service-task OUTPUT merge > 1MiB \u2014 3-strike poison on the branch (distinct from join-overlay poison), boundary timer left armed", axes: ["Error:poison", "Error:payloadLimit", "Concurrency:overlay", "Events:boundaryTimer"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/integration/saga-poison-job.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-LOOP-INBRANCH-01", title: "Loop wholly inside a parallel branch \u2014 per-branch occurrence keying", axes: ["Loops:occurrence", "Concurrency:fan-out", "Gateways:exclusiveGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/caps-loops.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-LOOP-LIMIT-BRANCH-01", title: "Loop inside a branch hits MAX_ELEMENT_OCCURRENCES -> loopLimit incident (not stepBudget)", axes: ["Loops:cap", "Error:loopLimit", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/caps-loops.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-DLQ-01", title: "Never-leased branch service job hits ACTIVATION_TTL_MS -> jobActivationTimeout via per-job JobScheduler DLQ, sibling frozen", axes: ["Error:jobActivationTimeout", "Concurrency:fan-out", "Replay:timer-self-heal", "Operator:cancel"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/caps-loops.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-BRANCH-RETRY-01", title: "Retryable /jobs/fail + full-jitter backoff + lease-expiry reclaim on an occurrence-keyed branch job, sibling proceeds, then exhaustion", axes: ["Retry:backoff", "Retry:reclaim", "Concurrency:fan-out", "Error:serviceTaskFailure"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/caps-loops.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-IDEMP-DUP-01", title: "Duplicate worker callback + duplicate message into ONE branch of a token set", axes: ["Idempotency:dupJob", "Idempotency:dupMessage", "Concurrency", "Replay:apply-from-D1"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/idempotency-operator.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-IDEMP-MSGTIMING-01", title: "Early-buffered and late message correlated into a token-set branch", axes: ["Idempotency:earlyBuffer", "Idempotency:late", "Events:messageCatch", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/idempotency-operator.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-OP-CANCEL-MIDFAN-01", title: "Operator /cancel mid-fan-out before any branch completes \u2014 empty-ledger operatorResolved", axes: ["Operator:cancel", "Concurrency", "Compensation"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/integration/parallel-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "C-OP-RETRY-COMPFAILED-01", title: "Operator /retry on compensationFailed in one lineage \u2014 re-drive from the failed compensator", axes: ["Operator:retry", "Compensation:failure", "Concurrency"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/idempotency-operator.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "W-AND-CRASH-01", title: "(WM-2) Crash mid-race -> re-walk fast-forwards committed branches without re-apply", axes: ["Replay:crash", "Concurrency:join-barrier", "Replay:fast-forward"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-AND-NEARSIM-01", title: "(WM-3) Swapped-order determinism \u2014 sequential A-then-B vs B-then-A reach a deep-equal final state (NOT a concurrent race; the concurrent dropped-tickle case is W-AND-TICKLE-GAP-01)", axes: ["Replay:multi-wait", "Concurrency:merge-order", "Replay:determinism"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-AND-TICKLE-GAP-01", title: "Two near-simultaneous bpmn_wake tickles \u2014 one consumed by wake#k, the second dropped in the inter-wait gap, recovered by the backstop (not a hang)", axes: ["Replay:multi-wait", "Replay:self-heal", "Concurrency:merge-order", "Replay:determinism"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-AND-BRANCHTIMEOUT-01", title: "(WM-4) One branch durable-wait times out while sibling live -> graceful escape, no unhandledRejection, no hang", axes: ["Replay:multi-wait", "Error:waitTimeout", "Concurrency"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-SELFHEAL-01", title: "Lost wake -> self-heal via timer-aware bounded backstop (result committed to D1, no tickle)", axes: ["Replay:self-heal", "Replay:apply-from-D1", "Concurrency:join-barrier"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-APPLYFROMD1-01", title: "Apply-from-D1 correctness \u2014 message/EBG payload applied from the D1 row, not the event", axes: ["Replay:apply-from-D1", "Events:messageCatch", "Idempotency:correlation"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-BUFFERED-STRAND-01", title: "Early-buffered message claimed at branch registration has NO apply-from-D1 provenance \u2014 terminated-Workflow inline re-drive strands it", axes: ["Replay:apply-from-D1", "Idempotency:earlyBuffer", "Events:messageCatch", "Replay:self-heal", "Concurrency:overlay"], legality: "valid", modes: ["workflow", "direct"], risk: "high", coverage: "new", phase: 3, directFile: "tests/integration/matrix/misc.test.ts", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-GWREUSE-01", title: "Gateway-decision reuse across real suspend/resume \u2014 OR activated-subset and XOR branch reused verbatim, never re-evaluated (promotes the simulated xor-replay harness to real CF)", axes: ["Replay:gateway-reuse", "Gateways:inclusiveGateway", "Gateways:exclusiveGateway", "Flows:conditional"], legality: "valid", modes: ["workflow"], risk: "med", coverage: "extends-existing", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-JOIN-FOLD-REPLAY-01", title: "Crash AFTER a join_completion is claimed but BEFORE the post-join leaf parks \u2014 replay must fast-forward the join WITHOUT re-folding branch overlays", axes: ["Replay:crash", "Replay:fast-forward", "Concurrency:join-barrier", "Concurrency:overlay", "Replay:determinism"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-COMP-CRASH-REPLAY-01", title: "Crash mid-compensation reverse pass under the single-wake barrier \u2014 replay must not re-run already-applied compensators", axes: ["Replay:crash", "Compensation:quiescence", "Replay:multi-wait", "Replay:fast-forward", "Concurrency"], legality: "valid", modes: ["workflow"], risk: "high", coverage: "extends-existing", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-WAKE-TERMINAL-01", title: "At-least-once bpmn_wake delivered to an already-terminal instance is a clean no-op (no re-drive, no duplicate history, no Workflow error)", axes: ["Idempotency:dupMessage", "Idempotency:dupJob", "Replay:self-heal", "Concurrency"], legality: "valid", modes: ["workflow"], risk: "med", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-TIMER-MIXED-BACKSTOP-01", title: "Timer-aware backstop with a MIXED frontier \u2014 one branch timer-waiting, one branch message-waiting; backstop must grow back when the branch timer fires/cancels (no hot re-walk loop)", axes: ["Replay:timer-self-heal", "Events:intermediateTimer", "Events:messageCatch", "Concurrency:fan-out", "Error:stepBudget"], legality: "valid", modes: ["workflow"], risk: "med", coverage: "new", phase: 3, directFile: "", workflowFile: "tests/workflow-mode/concurrency.wf.test.ts" },
  { id: "W-REG-LINEAR-01", title: "Single-token regression \u2014 linear Start->Service->Receive->End suspend/resume in Workflow mode", axes: ["Replay:single-token", "Activities:serviceTask", "Activities:receiveTask"], legality: "valid", modes: ["workflow"], risk: "med", coverage: "extends-existing", phase: 2, directFile: "", workflowFile: "tests/workflow-mode/regression.wf.test.ts" },
  { id: "W-REG-TIMER-01", title: "Single-token regression \u2014 boundary timer backstop on a real Workflow (timer-aware sizing)", axes: ["Replay:single-token", "Events:boundaryTimer", "Replay:timer-self-heal"], legality: "valid", modes: ["workflow"], risk: "med", coverage: "extends-existing", phase: 2, directFile: "", workflowFile: "tests/workflow-mode/regression.wf.test.ts" },
  { id: "R-BOUNDARY-ON-GW-01", title: "Boundary event attached to a parallel/inclusive/exclusive gateway -> publish reject", axes: ["Events:boundary", "Gateways", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-MERGE-UNCONTROLLED-01", title: "Uncontrolled merge \u2014 task with >1 incoming flow inside a region -> reject", axes: ["Concurrency:merge", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-JOIN-MISMATCH-01", title: "Mismatched join type \u2014 AND split closed by an inclusive join (or vice-versa) -> reject", axes: ["Gateways:parallelGateway", "Gateways:inclusiveGateway", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-JOIN-NOFORK-01", title: "Dangling multi-incoming parallel/inclusive JOIN with no matching split -> publish reject", axes: ["Gateways:parallelGateway", "Gateways:inclusiveGateway", "Concurrency:merge", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-MERGE-NONLAMINAR-01", title: "Two regions partially overlap (non-laminar nesting) -> reject", axes: ["Concurrency:nesting", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-LOOP-CROSS-01", title: "Loop (sequence flow) crossing a region boundary -> reject", axes: ["Loops", "Concurrency:confinement", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-SAMEMSG-01", title: "Same message name awaited by two concurrent branches -> reject", axes: ["Events:messageCatch", "Idempotency:correlation", "Concurrency", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-INSTANTIATE-01", title: "instantiate=\"true\" on a parallel/inclusive gateway, EBG, or receiveTask -> reject", axes: ["Activities:receiveTask", "Gateways", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-NONINT-TIMER-01", title: "Non-interrupting boundary timer (cancelActivity=\"false\") -> reject", axes: ["Events:boundaryTimer", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-COND-OFF-XOR-01", title: "conditionExpression on a flow not leaving an exclusive/inclusive gateway -> reject", axes: ["Flows:conditional", "Gateways:parallelGateway", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-BRANCH-ESCAPE-01", title: "Branch escape \u2014 a node inside the region edges to a target outside the region not through the join -> reject (covers the unreachable branch-internal cancel-end)", axes: ["Concurrency:confinement", "Events:cancelEnd", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "high", coverage: "extends-existing", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "S-SUBPROC-LINEAR-01", title: "Plain embedded subProcess on the token path \u2014 enter/exit bookkeeping + occurrence fast-forward", axes: ["Activities:subProcess"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/subprocess-walk.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "S-COMP-NESTED-COMMIT-01", title: "outer-tx > subProcess > inner-tx-commits; outer cancel compensates the inner rows reverse-by-global-seq (M5-L1 gate 1)", axes: ["Compensation:commit-shield", "Compensation:scope-nesting", "Activities:subProcess", "Activities:transaction"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/nested-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "S-COMP-REENTRY-SHIELD-01", title: "M2 cycle re-enters a committed nested tx \u2014 self-cancel shielded, ancestor cancel compensates every occurrence (M5-L1 gate 4)", axes: ["Compensation:commit-shield", "Loops:occurrence", "Activities:transaction"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/nested-compensation.test.ts", workflowFile: "" },
  { id: "S-ERR-BUBBLE-01", title: "Uncaught task error climbs the scope chain to a subProcess boundary; none anywhere \u2192 Hazard", axes: ["Events:errorBoundary", "Error:bubbling", "Activities:subProcess"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/scope-error-bubbling.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "S-ERR-END-01", title: "Error end event throws from a subProcess to the scope boundary; at root \u2192 uncaughtError incident", axes: ["Events:errorEnd", "Error:bubbling"], legality: "valid", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/error-end-event.test.ts", workflowFile: "" },
  { id: "S-TX-TIMER-01", title: "Timer boundary on a transaction \u2014 interrupt WITHOUT compensation, retained ledger, /cancel forces the reverse pass (M5-L1 gate 3)", axes: ["Events:boundaryTimer", "Activities:transaction", "Compensation:retained-ledger", "Operator:cancel"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/scope-boundary-timer.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "R-EVENT-SUBPROC-01", title: "Event subprocess (triggeredByEvent) -> interim publish reject (M5-L4 pointer)", axes: ["Activities:subProcess", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-MI-SUBPROC-01", title: "Multi-instance subProcess BODY containing a receiveTask -> v1 body-whitelist publish reject (flipped from the pre-L3 interim reject: MI-subProcess itself now publishes)", axes: ["Activities:multiInstance", "Activities:subProcess", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-SCOPE-DEPTH-01", title: "Scope nesting depth 9 > MAX_SCOPE_DEPTH -> publish reject", axes: ["Activities:subProcess", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "low", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-COMP-NO-TX-ANCESTOR-01", title: "isForCompensation handler with no transaction ancestor -> publish reject (no trigger)", axes: ["Compensation", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  { id: "R-CANCEL-END-SUBPROC-01", title: "Cancel end whose immediate scope is a subProcess -> publish reject", axes: ["Events:cancelEnd", "Activities:subProcess", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/matrix/reject.test.ts", workflowFile: "" },
  // M5-L2 (callActivity) — Task 12: registry wave over Tasks 3 + 6-10's coverage,
  // plus the reverse-path crash/idempotency scenarios this task adds directly in
  // tests/integration/matrix/call-activity.test.ts. Workflow-mode markers are
  // Task 14's — declared here (phase discipline mirrors every other dual-mode
  // row) but not yet authored; see that task's own gate.
  { id: "CA-FWD-01", title: "callActivity forward lifecycle — child instance created, output merged both ways, parent completes", axes: ["Activities:callActivity"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-forward.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-IDEMP-REDRIVE-01", title: "Cold inline re-drive of a completed callActivity parent is write-free (history/child unchanged)", axes: ["Activities:callActivity", "Idempotency:dupJob", "Replay:apply-from-D1"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/matrix/call-activity.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-ERR-BOUNDARY-01", title: "Child settles 'errored' — own error boundary on call1 routes the parent (never a child-local incident)", axes: ["Activities:callActivity", "Events:errorBoundary", "Error:routing"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-errors.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-INCIDENT-RETRY-01", title: "Cascading operator /retry heals the DEEPEST (grandchild) forward incident first, skipping an ancestor with nothing of its own", axes: ["Activities:callActivity", "Operator:retry", "Error:serviceTaskFailure"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-operator.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-HAZARD-TIMER-01", title: "Timer Hazard directly on a callActivity — fires, cascade-cancels the running child, NO compensation, ledger retained", axes: ["Activities:callActivity", "Events:boundaryTimer", "Error:Hazard"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-drain.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-COMP-CHILD-01", title: "A committed callActivity compensates by driving the child's OWN reverse pass, in order before the parent's earlier step", axes: ["Activities:callActivity", "Compensation:child-reverse"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-COMP-FAILED-01", title: "A child compensationFailed surfaces as the PARENT's own compensationFailure incident on the callActivity", axes: ["Activities:callActivity", "Compensation:failure", "Error:compensationFailure"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-COMP-NOOP-01", title: "No-op compensator — an empty-ledger committed child settles compensated immediately, no comp job, no park", axes: ["Activities:callActivity", "Compensation:child-reverse"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-compensation.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-COMP-CRASH-01", title: "Parent re-drive mid child-compensation re-parks on 'compensating' — no double CAS, no duplicate comp job", axes: ["Activities:callActivity", "Compensation:child-reverse", "Replay:crash", "Idempotency:dupCompensation"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/call-activity.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-DRAIN-RETAIN-01", title: "Inner-scope drain cancels a running child; the OUTER tx's later reverse still compensates the child's committed steps (drain retention)", axes: ["Activities:callActivity", "Compensation:child-reverse", "Concurrency:AND", "Events:errorBoundary"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/call-activity.test.ts", workflowFile: "" },
  { id: "CA-ROOTSCOPE-CANCEL-01", title: "A scope-less parent whose ONLY compensable content is the callActivity visit: operator cancel reverses the child (root-scope ledger visibility)", axes: ["Activities:callActivity", "Compensation:child-reverse", "Operator:cancel"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/matrix/call-activity.test.ts", workflowFile: "" },
  { id: "CA-OP-CHILD-409-01", title: "Direct /cancel and /retry on a callActivity CHILD both 409, naming the parent (all control flows through the saga root)", axes: ["Activities:callActivity", "Operator:cancel", "Operator:retry"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-operator.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "CA-REJECT-MSG-01", title: "A callActivity's resolved call tree contains a message wait (receiveTask / message intermediateCatch) — publish reject", axes: ["Activities:callActivity", "Events:messageCatch", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-publish.test.ts", workflowFile: "" },
  { id: "CA-REJECT-DEPTH-01", title: "Call-tree depth exceeds MAX_CALL_DEPTH=4 — publish reject", axes: ["Activities:callActivity", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "low", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-publish.test.ts", workflowFile: "" },
  { id: "CA-REJECT-UNRESOLVED-01", title: "calledElement does not resolve to any published process — publish reject naming the call activity and the target", axes: ["Activities:callActivity", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/call-activity-publish.test.ts", workflowFile: "" },
  // M5-L3 (multiInstance) — Task 13: registry wave over Tasks 2-12's coverage.
  // Direct-mode markers live in the per-task tests/integration/multi-instance-*
  // suites; workflow-mode (Layer B) re-runs live in matrix.wf.test.ts — live
  // where the terminal is tickle-reachable, @needs-real-cf / @needs-override
  // skips following the same automation boundary as the C-*/CA-* waves.
  { id: "MI-PAR-TASK-01", title: "Parallel cardinality MI on a serviceTask — 3 concurrent iteration jobs, index-ordered aggregation regardless of completion order", axes: ["Activities:multiInstance", "Activities:serviceTask", "MI:parallel", "MI:aggregation"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-forward.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-SEQ-COLL-01", title: "Sequential collection MI — one leasable iteration at a time, item/loopCounter seeded, items snapshot pinned once", axes: ["Activities:multiInstance", "MI:sequential", "MI:collection", "MI:aggregation"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-forward.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-ZERO-01", title: "Empty collection (N=0) — the visit settles immediately with results = [] and zero iteration jobs", axes: ["Activities:multiInstance", "MI:zero-cardinality"], legality: "valid", modes: ["direct", "workflow"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-forward.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-CAP-01", title: "Cardinality above the body-aware MAX_MI_CARDINALITY cap — graceful terminal miCardinality incident, no jobs created", axes: ["Activities:multiInstance", "MI:caps", "Error:miCardinality"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-forward.test.ts", workflowFile: "" },
  { id: "MI-PAR-SUB-01", title: "Parallel MI over a subProcess body — per-iteration branch tokens, interior gateway decisions occurrence-distinct, overlay-isolated aggregation", axes: ["Activities:multiInstance", "Activities:subProcess", "MI:parallel", "Concurrency:overlay", "Gateways:exclusiveGateway"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-subprocess.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-SEQ-SUB-01", title: "Sequential collection MI over a subProcess body — one iteration's interior jobs at a time, no root-variable leak mid-flight", axes: ["Activities:multiInstance", "Activities:subProcess", "MI:sequential"], legality: "valid", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-subprocess.test.ts", workflowFile: "" },
  { id: "MI-COND-EARLY-01", title: "completionCondition early settle — k of N completes the visit, remaining iterations NORMALLY discarded (never compensation)", axes: ["Activities:multiInstance", "MI:completionCondition"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-condition.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-COND-LEDGER-01", title: "Early-settled MI inside a transaction that later cancels — exactly the finished iterations compensate, the discarded ones ledger nothing", axes: ["Activities:multiInstance", "MI:completionCondition", "Compensation", "Activities:transaction"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-condition.test.ts", workflowFile: "" },
  { id: "MI-ERR-BOUNDARY-01", title: "Iteration business error — abort settles once, in-flight iterations drain, the error routes the boundary on the MI element", axes: ["Activities:multiInstance", "Events:errorBoundary", "Error:routing"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-errors.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-HAZARD-TIMER-01", title: "Timer boundary on an MI activity = Hazard — interrupt WITHOUT compensation, retained rows compensable by a later /cancel", axes: ["Activities:multiInstance", "Events:boundaryTimer", "Error:Hazard", "Compensation:retained-ledger", "Operator:cancel"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-errors.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-CALL-FANOUT-01", title: "MI over callActivity — N iteration-keyed real child instances, item/loopCounter seeded, child finals aggregated by index", axes: ["Activities:multiInstance", "Activities:callActivity", "MI:parallel", "MI:aggregation"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-call.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-CALL-COMP-01", title: "MI-callActivity inside a cancelled transaction — the parent reverse pass drives EACH iteration child's own reverse pass, reverse seq order", axes: ["Activities:multiInstance", "Activities:callActivity", "Compensation:child-reverse", "Activities:transaction"], legality: "valid", modes: ["direct", "workflow"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-call.test.ts", workflowFile: "tests/workflow-mode/matrix.wf.test.ts" },
  { id: "MI-CALL-ERR-01", title: "One iteration child settles errored — siblings cascade-cancelled, the business error routes at the parent's MI boundary", axes: ["Activities:multiInstance", "Activities:callActivity", "Events:errorBoundary", "Error:routing"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-call.test.ts", workflowFile: "" },
  { id: "MI-COMP-REVERSE-01", title: "Per-iteration compensation of a serviceTask MI in a cancelled tx — N comp jobs, reverse seq order, iteration-keyed", axes: ["Activities:multiInstance", "Compensation:per-lineage-reverse", "Activities:transaction"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-compensation.test.ts", workflowFile: "" },
  { id: "MI-COMP-STRAGGLER-01", title: "Cancel mid-fan-out with an iteration still in flight — two-phase cancel abandons it, finished iterations compensate, barrier releases", axes: ["Activities:multiInstance", "Compensation:straggler", "Operator:cancel"], legality: "valid", modes: ["direct"], risk: "high", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-compensation.test.ts", workflowFile: "" },
  { id: "MI-LINEAGE-01", title: "Lineage block over an MI fan-out — children carry iterationIndex; root /retry cascade + direct-child 409 unchanged over iterations", axes: ["Activities:multiInstance", "Activities:callActivity", "Operator:retry", "Operator:cancel"], legality: "valid", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-operator.test.ts", workflowFile: "" },
  { id: "MI-REJECT-DATABINDING-01", title: "Standard MI data bindings (loopDataInputRef/inputDataItem) — permanent publish reject", axes: ["Activities:multiInstance", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-publish.test.ts", workflowFile: "" },
  { id: "MI-REJECT-NOSOURCE-01", title: "multiInstanceLoopCharacteristics with no recognized cardinality source — publish reject", axes: ["Activities:multiInstance", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-publish.test.ts", workflowFile: "" },
  { id: "MI-REJECT-BODY-01", title: "MI-subProcess body containing a receiveTask — v1 body-whitelist publish reject", axes: ["Activities:multiInstance", "Activities:subProcess", "Legality:reject"], legality: "reject", modes: ["direct"], risk: "med", coverage: "new", phase: 1, directFile: "tests/integration/multi-instance-publish.test.ts", workflowFile: "" },
];
